version: '3'

services:
  postgres:
    image: postgres-image
    build:
        context: ./MarcasAutos.Infrastructure
    ports:
      - "5432:5432"
    container_name: postgres-container
    environment:
      POSTGRES_DB: testCarBrands
      POSTGRES_USER: danilo
      POSTGRES_PASSWORD: danilo.
  myapi:
    image: api-image  
    build:
        context: .
        dockerfile: MarcasAutos/Dockerfile
    ports:
        - "5434:80"
    container_name: api-container
    restart: on-failure
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-container;Port=5432;Database=testCarBrands;Username=danilo;Password=danilo.;
    depends_on:
        - postgres